[schema]
url = "https://metadata-db-runtime-675766508318.asia-south1.run.app"
lang = "Rust"
orm = "Diesel"
root = "src/models"
schema_id = "66bbad42-200f-4b2f-ba0d-9feb1f3edbfa"
cache_schema_id = "a3f5e631-8225-4ac5-85b9-71ecd107bb6c"
branch = "stage"

[tables]
names = ["dbschema", "dbschema_branch", "templates", "service", "service_envs", "package", "package_env", "organization", "snapshots"]
