[schema]
url = "http://localhost:8001"
lang = "Rust"
orm = "Diesel"
root = "src/models"
schema_id = "0571964c-0da3-4bf1-84d3-041797650ffc"
branch = "main"

[tables]
names = ["dbschema", "dbschema_branch", "templates", "service", "service_envs", "package"]
