[schema]
url = "https://metadata-db-runtime-675766508318.asia-south1.run.app"
lang = "Rust"
orm = "Diesel"
root = "src/models"
schema_id = "885bde8a-5247-46f1-958c-a7d30fb06deb"
cache_schema_id = "f0604500-6e42-4604-af80-784a3e74a50c"
branch = "stage"

[tables]
names = ["dbschema", "dbschema_branch", "templates", "service", "service_envs", "package", "package_env", "organization", "snapshots"]
