[settings]
git_url_prefix = "https://github.com/ginger-society/metadata-service-backend"
take_snapshots = false

[version]
channel = "Nightly"
major = 0
minor = 6
patch = 0
revision = 0

[[references]]
file_name = "Cargo.toml"
output_type = "String"
variable = "version"
