[debug]
# You should generate your own by "openssl rand -base64 32"
port = 8081
secret_key = "Yuvzw+jJ4yzKHi/JwHFl1y4X6Tjn/WrskHOWrlvt/L0="

[release]
address = "0.0.0.0"
keep_alive = 5
limits = {forms = 32768}
log_level = "critical"
port = 8081
read_timeout = 5
secret_key = "wAH6XoauwlQ0DZM65+LivbFo2j14mJ48iy2PC+hW+es="
write_timeout = 5

[global]
address = "${ROCKET_ADDRESS:0.0.0.0}"
port = "${ROCKET_PORT:8000}"
